### ISSUE TITLE
Can't update profile

### ISSUE THREAD

**Issue by JonEsparaz** [jesus-collective/mobile#110]
If I make an edit, then click Save and Publish, leave, then return to my profile, the changes are not reflected.

```
{data: null, errors: Array(1)}
   data: null
   errors: Array(1)
      0:
         locations: null
         message: "The variables input contains a field name 'organizations' that is not defined for input object type 'UpdateUserInput' "
         path: null
```
